require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaymentsDocumentsController do

  # This should return the minimal set of attributes required to create a valid
  # PaymentsDocument. As you add validations to PaymentsDocument, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaymentsDocumentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all payments_documents as @payments_documents" do
      payments_document = PaymentsDocument.create! valid_attributes
      get :index, {}, valid_session
      assigns(:payments_documents).should eq([payments_document])
    end
  end

  describe "GET show" do
    it "assigns the requested payments_document as @payments_document" do
      payments_document = PaymentsDocument.create! valid_attributes
      get :show, {:id => payments_document.to_param}, valid_session
      assigns(:payments_document).should eq(payments_document)
    end
  end

  describe "GET new" do
    it "assigns a new payments_document as @payments_document" do
      get :new, {}, valid_session
      assigns(:payments_document).should be_a_new(PaymentsDocument)
    end
  end

  describe "GET edit" do
    it "assigns the requested payments_document as @payments_document" do
      payments_document = PaymentsDocument.create! valid_attributes
      get :edit, {:id => payments_document.to_param}, valid_session
      assigns(:payments_document).should eq(payments_document)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PaymentsDocument" do
        expect {
          post :create, {:payments_document => valid_attributes}, valid_session
        }.to change(PaymentsDocument, :count).by(1)
      end

      it "assigns a newly created payments_document as @payments_document" do
        post :create, {:payments_document => valid_attributes}, valid_session
        assigns(:payments_document).should be_a(PaymentsDocument)
        assigns(:payments_document).should be_persisted
      end

      it "redirects to the created payments_document" do
        post :create, {:payments_document => valid_attributes}, valid_session
        response.should redirect_to(PaymentsDocument.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payments_document as @payments_document" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentsDocument.any_instance.stub(:save).and_return(false)
        post :create, {:payments_document => { "id" => "invalid value" }}, valid_session
        assigns(:payments_document).should be_a_new(PaymentsDocument)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentsDocument.any_instance.stub(:save).and_return(false)
        post :create, {:payments_document => { "id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payments_document" do
        payments_document = PaymentsDocument.create! valid_attributes
        # Assuming there are no other payments_documents in the database, this
        # specifies that the PaymentsDocument created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PaymentsDocument.any_instance.should_receive(:update_attributes).with({ "id" => "MyString" })
        put :update, {:id => payments_document.to_param, :payments_document => { "id" => "MyString" }}, valid_session
      end

      it "assigns the requested payments_document as @payments_document" do
        payments_document = PaymentsDocument.create! valid_attributes
        put :update, {:id => payments_document.to_param, :payments_document => valid_attributes}, valid_session
        assigns(:payments_document).should eq(payments_document)
      end

      it "redirects to the payments_document" do
        payments_document = PaymentsDocument.create! valid_attributes
        put :update, {:id => payments_document.to_param, :payments_document => valid_attributes}, valid_session
        response.should redirect_to(payments_document)
      end
    end

    describe "with invalid params" do
      it "assigns the payments_document as @payments_document" do
        payments_document = PaymentsDocument.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentsDocument.any_instance.stub(:save).and_return(false)
        put :update, {:id => payments_document.to_param, :payments_document => { "id" => "invalid value" }}, valid_session
        assigns(:payments_document).should eq(payments_document)
      end

      it "re-renders the 'edit' template" do
        payments_document = PaymentsDocument.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentsDocument.any_instance.stub(:save).and_return(false)
        put :update, {:id => payments_document.to_param, :payments_document => { "id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payments_document" do
      payments_document = PaymentsDocument.create! valid_attributes
      expect {
        delete :destroy, {:id => payments_document.to_param}, valid_session
      }.to change(PaymentsDocument, :count).by(-1)
    end

    it "redirects to the payments_documents list" do
      payments_document = PaymentsDocument.create! valid_attributes
      delete :destroy, {:id => payments_document.to_param}, valid_session
      response.should redirect_to(payments_documents_url)
    end
  end

end
